// AStefanov
node {
    stage('Scm Checkout'){
        git credentialsId: 'git-x', url: 'repo-url'
        sh "git checkout master"

    }

    stage ('Build Docker Image') {
        sh 'docker build -t x_api .'
    }
        stage ('Remove old Docker Image') {
            sh ''' echo "Removiendo antiguos contenedores"
            docker rm x_api_test -f
            docker rm x_api_stg -f
            docker rm x_api_prod -f
            '''
    }    
    stage('Run  Docker Container'){
        sh ''' echo "Corriendo nuevos contenedores"
            docker run -it -dp 5500:3333 --env-file ./server/.env.test --name x_api_test x_api
            docker run -it -dp 5600:3333 --env-file ./server/.env.stg --name x_api_stg x_api
            docker run -it -dp 5700:3333 --env-file ./server/.env.prod --name x_api_prod x_api
        '''
    }
}
