// AStefanov
node {
    stage('Scm Checkout'){
        git credentialsId: 'git-x', url: 'repo-ur'
        sh "git checkout master"

    }
    stage ('Env settings'){
        sh 'cp .env.example .env'
    }
    stage ('Build Docker Image') {
        sh 'docker build -t web_app .'
    }
        stage ('Remove old Docker Image') {
            sh ''' echo "Removiendo antiguos contenedores"
            docker rm web_app_test -f
            docker rm web_app_stg -f
            docker rm web_app_prod -f
            '''
    }    
    stage('Run  Docker Container'){
        sh ''' echo "Corriendo nuevos contenedores"
        docker run -dp 5701:80 --name web_app_test --env-file ./.env.test web_app
        docker run -dp 5601:80 --name web_app_stg --env-file ./.env.stg web_app
        docker run -dp 5501:80 --name web_app_prod --env-file ./.env.prod web_app

        '''
    }
}
