pipeline {
    agent any

    stages {
        stage('SCM Checkout - Clonar repositorio del proyecto') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/tags/*']],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [[$class: 'CloneOption', noTags: false, reference: '', shallow: false, timeout: 60]],
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: 'git-x', url: 'repo-url']]])
            }
        }

        stage('Build - Construir imagen Docker') {
            steps {
                // Obtener el último tag liberado
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0 origin/master', returnStdout: true).trim()
                    // Construir la imagen Docker con el tag obtenido
                    sh "docker build -t x_api:${lastTag} ."
                }
            }
        }

        stage('Pruebas - Ejecutar PyTest') {
            steps {
                // Obtener el último tag liberado
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0', returnStdout: true).trim()
                    // Ejecutar pruebas en la imagen Docker construida
                    sh "docker run x_api:${lastTag} pytest -v"
                }
            }
        }
        stage('Iniciar sesión en la registry') {
            steps {
                // Iniciar sesión en la registry
                withCredentials([usernamePassword(credentialsId: 'registry-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login registry-url -u $USERNAME -p $PASSWORD'
                }
            }
        }

        stage('Etiquetar imagen Docker') {
            steps {
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0', returnStdout: true).trim()
                    sh "docker tag x_api:${lastTag} registry-url/x_api:${lastTag}"
                }
            }
        }

        stage('Subir imagen Docker a Registry') {
            steps {
                // Subir la imagen Docker con el tag obtenido
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0 origin/master', returnStdout: true).trim()
                    sh "docker push registry-url/x_api:${lastTag}"
                }
            }
        }

        stage('Deploy - Desplegar imagen Docker') {
            steps {
                // Obtener el último tag liberado
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0', returnStdout: true).trim()
                    // Detener y eliminar el contenedor existente (si lo hay)
                    sh "docker stop x_api || true"
                    sh "docker rm x_api || true"
                    // Descargar la última imagen Docker desde la registry
                    sh "docker pull registry-url/x_api:${lastTag}"
                    // Iniciar un nuevo contenedor con la nueva imagen
                    sh "docker run -d -p 5000:3333 --env-file /directory/env/.env --name x_api x_api:${lastTag}"
                }
            }
        }
    }
}
