pipeline {
    agent any

    stages {
        stage('SCM Checkout - Clonar repositorio de Docker') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: '*/tags/*']],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [[$class: 'CloneOption', noTags: false, reference: '', shallow: false, timeout: 60]],
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: 'git-rafam', url: 'https://www.git.rafam.ec.gba.gov.ar/rafam-2/rafam_tablero_api']]])
            }
        }

        stage('Build - Construir imagen Docker') {
            steps {
                // Obtener el último tag liberado
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0 origin/master', returnStdout: true).trim()
                    // Construir la imagen Docker con el tag obtenido
                    sh "docker build -t rafam_tablero_api:${lastTag} ."
                }
            }
        }

        stage('Pruebas - Ejecutar PyTest') {
            steps {
                // Obtener el último tag liberado
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0', returnStdout: true).trim()
                    // Ejecutar pruebas en la imagen Docker construida
                    sh "docker run rafam_tablero_api:${lastTag} pytest -v"
                }
            }
        }
        stage('Iniciar sesión en la registry') {
            steps {
                // Iniciar sesión en la registry
                withCredentials([usernamePassword(credentialsId: 'registry-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login www.registry-tableros.rafam.ec.gba.gov.ar -u $USERNAME -p $PASSWORD'
                }
            }
        }

        stage('Etiquetar imagen Docker') {
            steps {
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0', returnStdout: true).trim()
                    sh "docker tag rafam_tablero_api:${lastTag} www.registry.rafam.ec.gba.gov.ar/rafam_tablero_api:${lastTag}"
                }
            }
        }

        stage('Subir imagen Docker a Registry') {
            steps {
                // Subir la imagen Docker con el tag obtenido
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0 origin/master', returnStdout: true).trim()
                    sh "docker push www.registry.rafam.ec.gba.gov.ar/rafam_tablero_api:${lastTag}"
                }
            }
        }

        stage('Deploy - Desplegar imagen Docker') {
            steps {
                // Obtener el último tag liberado
                script {
                    def lastTag = sh(script: 'git describe --tags --abbrev=0', returnStdout: true).trim()
                    // Detener y eliminar el contenedor existente (si lo hay)
                    sh "docker stop rafam_tablero_api || true"
                    sh "docker rm rafam_tablero_api || true"
                    // Descargar la última imagen Docker desde la registry
                    sh "docker pull www.registry.rafam.ec.gba.gov.ar/rafam_tablero_api:${lastTag}"
                    // Iniciar un nuevo contenedor con la nueva imagen
                    sh "docker run -d -p 5000:3333 --env-file /home/tmu/ci_cd/env/.env.back --name rafam_tablero_api rafam_tablero_api:${lastTag}"
                }
            }
        }
    }
}
