pipeline {
    agent any

    stages {
        stage('Clonar repositorio') {
            steps {
                // Clonar el repositorio
                checkout([$class: 'GitSCM', 
                        branches: [[name: 'v1.5.2.1-dev']], 
                        doGenerateSubmoduleConfigurations: false, 
                        extensions: [], 
                        submoduleCfg: [], 
                        userRemoteConfigs: [[credentialsId: 'git-x', url: 'repository-url']]])
            }
        }

        stage('Construir imagen Docker') {
            steps {
                // Construir la imagen Docker
                sh 'docker build -t x_api:v1.5.2.1-dev .'
            }
        }

        stage('Iniciar sesión en la registry') {
            steps {
                // Iniciar sesión en la registry
                withCredentials([usernamePassword(credentialsId: 'registry-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login registry-url -u $USERNAME -p $PASSWORD'
                }
            }
        }

        stage('Etiquetar imagen Docker') {
            steps {
                // Etiquetar la imagen Docker
                sh 'docker tag x_api:v1.5.2.1-dev registry-url/x_api:v1.5.2.1-dev'
            }
        }

        stage('Subir imagen Docker a la registry') {
            steps {
                // Subir la imagen Docker a la registry
                sh 'docker push registry-url/x_api:v1.5.2.1-dev'
            }
        }

        stage('Desplegar imagen Docker en servidor') {
            steps {
                // Pull de la imagen Docker en el servidor
                sh "docker pull registry-url/x:v1.5.2.1-dev"

                // Detener y eliminar contenedores existentes
                sh "docker stop x_api:v1.5.2.1-dev || true && docker rm x_api:v1.5.2.1-dev || true"

                // Ejecutar contenedor con la nueva imagen
                sh "docker run -it -dp 5000:3333 --env-file /directory/.env --name x_api x_api:v1.5.2.1-dev"
            }
        }
    }
}
